name: tenfit
favicon: null
layout_spectrum: 0.7795815700665116
typography_spectrum: 0.22265372634865344
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5361948790960014
  lightness: 0.9322577428538352
  saturation: 0.1715913601219654
  rhythmicContrast: 0.6341620592866093
purpose: []
